/* The two documents a site that collects enquiries must publish.
 *
 * They were missing entirely: the footer had nowhere to link and the lead
 * form collected a name, a phone number and an email with no policy behind
 * it. The text describes what this system actually does — the fields the
 * form stores, the single admin session cookie, the masking and the audit
 * trail on revealing a contact — so it stays true as long as the code does.
 * The team should still have it reviewed before relying on it.
 */
export const LEGAL_PAGES: { slug: string; title: string; content: Record<string, { title: string; body: string; done: boolean }> }[] = [
  {
    slug: "privacy",
    title: "นโยบายความเป็นส่วนตัว",
    content: {
      th: { title: "นโยบายความเป็นส่วนตัว", body: "<p>บริษัท เจเคพี พร็อพเพอร์ตี้ จำกัด (JKP PROPERTY CO., LTD.) ให้ความสำคัญกับข้อมูลส่วนบุคคลของผู้ใช้งานเว็บไซต์ jkppropertyagency.com นโยบายนี้อธิบายว่าเราเก็บข้อมูลอะไร เก็บไปทำอะไร และท่านมีสิทธิอะไรบ้าง ตาม พ.ร.บ. คุ้มครองข้อมูลส่วนบุคคล พ.ศ. 2562 (PDPA)</p><h3>1. ข้อมูลที่เราเก็บ</h3><p>เราเก็บเฉพาะข้อมูลที่ท่านกรอกให้เราเองผ่านแบบฟอร์มบนเว็บไซต์ ได้แก่ <b>ชื่อ</b> · <b>เบอร์โทรศัพท์</b> · <b>อีเมล</b> · <b>ชื่อบริษัท</b> · <b>ข้อความหรือรายละเอียดความต้องการ</b> (เช่น ประเภททรัพย์ ขนาดพื้นที่ งบประมาณ ทำเลที่สนใจ)</p><p>ชื่อและเบอร์โทรศัพท์เป็นข้อมูลที่จำเป็น เพราะเป็นช่องทางที่ทีมงานใช้ติดต่อกลับ ส่วนข้อมูลอื่นท่านจะกรอกหรือไม่ก็ได้</p><h3>2. คุกกี้และการติดตาม</h3><p>เว็บไซต์ส่วนที่เปิดให้บุคคลทั่วไปเข้าชม <b>ไม่มีการติดตั้งเครื่องมือติดตามพฤติกรรม ไม่มีระบบวิเคราะห์ผู้เข้าชม และไม่มีคุกกี้โฆษณา</b> คุกกี้เดียวที่ระบบสร้างขึ้นคือคุกกี้สำหรับรักษาสถานะการเข้าสู่ระบบของเจ้าหน้าที่ผู้ดูแลระบบเท่านั้น ผู้เข้าชมทั่วไปจะไม่ได้รับคุกกี้นี้</p><p>บริการของบุคคลภายนอกที่เกี่ยวข้องมีสองอย่าง คือ <b>แผนที่ Google ที่ฝังในหน้าติดต่อเรา</b> ซึ่งจะโหลดก็ต่อเมื่อท่านกดอนุญาตเท่านั้น และ <b>ฟอนต์จาก Google Fonts</b> ซึ่งไม่สร้างคุกกี้ รายละเอียดทั้งหมดอยู่ใน<a href=\"/th/p/cookies\">นโยบายคุกกี้</a></p><h3>3. วัตถุประสงค์ในการใช้ข้อมูล</h3><p>เราใช้ข้อมูลของท่านเพื่อ ติดต่อกลับตามที่ท่านร้องขอ · คัดเลือกทรัพย์ที่ตรงกับความต้องการ · จัดนัดหมายเข้าชมทรัพย์ · ดำเนินการเจรจาและจัดทำสัญญาเช่าหรือซื้อขาย เท่านั้น</p><h3>4. การเปิดเผยข้อมูล</h3><p><b>เราไม่ขาย ไม่ให้เช่า และไม่แลกเปลี่ยนข้อมูลของท่านกับบุคคลภายนอกเพื่อการตลาด</b> เราจะเปิดเผยข้อมูลเท่าที่จำเป็นให้แก่เจ้าของทรัพย์หรือผู้ให้เช่าเฉพาะเมื่อต้องจัดนัดเข้าชมหรือทำสัญญา และเปิดเผยต่อหน่วยงานรัฐเมื่อมีหน้าที่ตามกฎหมาย</p><h3>5. การเข้าถึงข้อมูลภายในองค์กร</h3><p>ระบบหลังบ้านจำกัดสิทธิ์การเข้าถึงตามบทบาทของพนักงาน โดยค่าเริ่มต้น <b>เบอร์โทรศัพท์และอีเมลจะถูกปิดบังบางส่วน</b> พนักงานที่ต้องการดูข้อมูลเต็มต้องกดเปิดดู และการเปิดดูทุกครั้งจะถูกบันทึกไว้ว่าใครเปิดดูเมื่อใด</p><h3>6. ระยะเวลาการเก็บรักษา</h3><p>เราเก็บข้อมูลไว้เท่าที่จำเป็นต่อการติดต่อและการปฏิบัติตามสัญญา รวมถึงระยะเวลาที่กฎหมายกำหนดให้เก็บเอกสารทางบัญชีและภาษี เมื่อพ้นความจำเป็นแล้วเราจะลบหรือทำให้ข้อมูลไม่สามารถระบุตัวบุคคลได้</p><h3>7. สิทธิของท่าน</h3><p>ท่านมีสิทธิขอเข้าถึงและขอสำเนาข้อมูลของท่าน · ขอแก้ไขให้ถูกต้อง · ขอลบหรือทำลาย · ขอให้ระงับการใช้ · คัดค้านการเก็บหรือใช้ · ขอถอนความยินยอม · และขอให้โอนย้ายข้อมูล ท่านสามารถใช้สิทธิได้โดยติดต่อเราตามช่องทางด้านล่าง เราจะดำเนินการภายใน 30 วัน</p><h3>8. ความปลอดภัย</h3><p>เว็บไซต์ให้บริการผ่าน HTTPS ข้อมูลถูกจัดเก็บในฐานข้อมูลที่เข้าถึงได้เฉพาะผู้ที่ได้รับสิทธิ์ และรหัสผ่านผู้ดูแลระบบถูกเข้ารหัสทางเดียว</p><h3>9. ติดต่อเรา</h3><p>หากมีคำถามเกี่ยวกับนโยบายนี้ หรือต้องการใช้สิทธิของท่าน ติดต่อ<a href=\"/th/contact\">หน้าติดต่อเรา</a> หรืออีเมล atsokoproperty.sales@gmail.com · โทร +66 80-830-4004</p><p><i>ปรับปรุงล่าสุด: 15 สิงหาคม 2569</i></p>", done: true },
      en: { title: "Privacy Policy", body: "<p>JKP PROPERTY CO., LTD. respects the personal data of everyone who uses jkppropertyagency.com. This policy explains what we collect, why, and what rights you have under Thailand's Personal Data Protection Act B.E. 2562 (PDPA).</p><h3>1. What we collect</h3><p>We collect only what you type into the forms on this site: <b>name</b> · <b>phone number</b> · <b>email</b> · <b>company name</b> · <b>your message or requirements</b> (property type, floor area, budget, preferred locations).</p><p>Name and phone number are required, because they are how our team gets back to you. Everything else is optional.</p><h3>2. Cookies and tracking</h3><p>The public side of this website carries <b>no behavioural tracking, no visitor analytics and no advertising cookies</b>. The only cookie the system sets is the session cookie that keeps a staff member signed in to the admin area. Ordinary visitors never receive it.</p><p>Two third-party services are involved: the <b>Google map embedded on the contact page</b>, which loads only after you allow it, and <b>Google Fonts</b>, which sets no cookie. Both are set out in full in our <a href=\"/en/p/cookies\">Cookie Policy</a>.</p><h3>3. Why we use it</h3><p>To reply to your enquiry · to shortlist properties that match what you asked for · to arrange viewings · and to negotiate and prepare a lease or sale agreement. Nothing else.</p><h3>4. Who we share it with</h3><p><b>We do not sell, rent or trade your data for marketing.</b> We pass on only what is necessary to a landlord or property owner when a viewing or an agreement requires it, and to government authorities where the law obliges us.</p><h3>5. Access inside our team</h3><p>Our internal system restricts access by staff role. By default <b>phone numbers and email addresses are partly masked</b>; a staff member who needs the full value must reveal it deliberately, and every reveal is recorded with who did it and when.</p><h3>6. How long we keep it</h3><p>For as long as we need it to stay in touch and to perform a contract, plus the period Thai accounting and tax law requires records to be kept. After that we delete it or render it non-identifying.</p><h3>7. Your rights</h3><p>You may ask for access and a copy of your data · correction · deletion · restriction of use · to object to our processing · to withdraw consent · and for data portability. Contact us using the details below and we will act within 30 days.</p><h3>8. Security</h3><p>The site is served over HTTPS. Data is held in a database reachable only by authorised accounts, and administrator passwords are stored as one-way hashes.</p><h3>9. Contact us</h3><p>Questions about this policy, or to exercise your rights: see our <a href=\"/en/contact\">contact page</a>, email atsokoproperty.sales@gmail.com, or call +66 80-830-4004.</p><p><i>Last updated: 15 August 2026</i></p>", done: true },
      zh: { title: "隐私政策", body: "<p>JKP PROPERTY CO., LTD.（泰国杰克普房地产有限公司）重视每一位 jkppropertyagency.com 使用者的个人资料。本政策说明我们收集哪些资料、用于何处，以及您依据泰国《个人资料保护法》（PDPA, B.E. 2562）享有的权利。</p><h3>1. 我们收集的资料</h3><p>仅限于您在本网站表单中自行填写的内容：<b>姓名</b>·<b>电话</b>·<b>电子邮箱</b>·<b>公司名称</b>·<b>留言或需求内容</b>（房源类型、面积、预算、意向区位）。</p><p>姓名与电话为必填，因为这是我们回复您的唯一途径；其余均为选填。</p><h3>2. Cookie 与追踪</h3><p>本网站面向公众的部分<b>不设行为追踪、不设访客分析、不设广告 Cookie</b>。系统唯一写入的 Cookie，是让管理人员保持后台登录状态的会话 Cookie，普通访客不会收到。</p><p>涉及的第三方服务共两项：<b>联系页面内嵌的 Google 地图</b>（仅在您允许后才会加载），以及<b>Google Fonts 字体</b>（不写入 Cookie）。详情请见<a href=\"/zh/p/cookies\">Cookie 政策</a>。</p><h3>3. 使用目的</h3><p>回复您的咨询·筛选符合您需求的房源·安排看房·以及洽谈并办理租赁或买卖合约。仅此而已。</p><h3>4. 资料的提供对象</h3><p><b>我们不会为营销目的出售、出租或交换您的资料。</b>仅在安排看房或签订合约确有必要时，向业主或出租方提供必要信息；并在法律要求时向主管机关提供。</p><h3>5. 团队内部的存取</h3><p>后台依职务限制存取权限。电话与邮箱<b>默认为部分遮蔽</b>，需要查看完整内容的同事必须主动点击显示，且每一次显示都会记录操作人与时间。</p><h3>6. 保存期限</h3><p>保存至联系与履行合约所必要的期间，并加上泰国会计与税务法规要求保存单据的期限。期满后我们会删除或做去识别化处理。</p><h3>7. 您的权利</h3><p>您可要求查阅并取得副本·更正·删除·限制使用·反对处理·撤回同意·以及资料可携。请以下列方式联系我们，我们将于 30 日内处理。</p><h3>8. 安全</h3><p>网站以 HTTPS 提供服务；资料存放于仅授权帐号可存取的数据库；管理员密码以单向散列方式保存。</p><h3>9. 联系我们</h3><p>如对本政策有疑问或欲行使权利，请见<a href=\"/zh/contact\">联系我们</a>页面，或发送邮件至 atsokoproperty.sales@gmail.com，电话 +66 80-830-4004。</p><p><i>最后更新：2026 年 8 月 15 日</i></p>", done: true },
    },
  },
  {
    slug: "terms",
    title: "ข้อกำหนดการใช้งาน",
    content: {
      th: { title: "ข้อกำหนดการใช้งาน", body: "<p>ข้อกำหนดนี้ใช้กับการเข้าชมและใช้งานเว็บไซต์ jkppropertyagency.com ซึ่งดำเนินการโดย บริษัท เจเคพี พร็อพเพอร์ตี้ จำกัด การใช้งานเว็บไซต์ถือว่าท่านยอมรับข้อกำหนดนี้</p><h3>1. ลักษณะของข้อมูลบนเว็บไซต์</h3><p>รายการทรัพย์ ราคา ขนาดพื้นที่ และรายละเอียดต่าง ๆ บนเว็บไซต์นี้จัดทำขึ้นเพื่อการนำเสนอเบื้องต้นเท่านั้น <b>ไม่ถือเป็นคำเสนอที่ผูกพันทางกฎหมาย</b> ราคาและสถานะว่างอาจเปลี่ยนแปลงได้ตลอดเวลา ทีมงานจะยืนยันข้อมูลล่าสุดอีกครั้งก่อนนัดเข้าชมและก่อนทำสัญญาทุกครั้ง</p><h3>2. การตรวจสอบก่อนทำสัญญา</h3><p>ก่อนตัดสินใจเช่าหรือซื้อ ท่านควรตรวจสอบเอกสารสิทธิ์ ใบอนุญาตที่เกี่ยวข้อง (เช่น ใบอนุญาตประกอบกิจการโรงงาน ร.ง.4) ผังเมือง และสภาพทรัพย์จริงด้วยตนเองหรือโดยที่ปรึกษาของท่าน บริษัทยินดีจัดหาเอกสารและพาเข้าชมทรัพย์ แต่ไม่อาจรับรองความถูกต้องของเอกสารที่ออกโดยบุคคลภายนอกได้</p><h3>3. การใช้งานที่ยอมรับได้</h3><p>ห้ามใช้เว็บไซต์เพื่อวัตถุประสงค์ที่ผิดกฎหมาย ห้ามดึงข้อมูลจำนวนมากโดยอัตโนมัติเพื่อนำไปใช้ในเชิงพาณิชย์ และห้ามพยายามเข้าถึงส่วนของระบบที่ไม่ได้เปิดให้สาธารณะ</p><h3>4. ทรัพย์สินทางปัญญา</h3><p>ข้อความ ภาพถ่าย ตราสัญลักษณ์ และการออกแบบบนเว็บไซต์เป็นของบริษัทหรือของเจ้าของทรัพย์ที่อนุญาตให้ใช้ ห้ามทำซ้ำหรือเผยแพร่ต่อเพื่อการค้าโดยไม่ได้รับอนุญาตเป็นลายลักษณ์อักษร</p><h3>5. ลิงก์ไปยังเว็บไซต์อื่น</h3><p>เว็บไซต์อาจมีลิงก์ไปยังแผนที่หรือบริการภายนอก บริษัทไม่รับผิดชอบต่อเนื้อหาและนโยบายของเว็บไซต์เหล่านั้น</p><h3>6. ข้อมูลส่วนบุคคล</h3><p>การเก็บและใช้ข้อมูลส่วนบุคคลเป็นไปตาม<a href=\"/th/p/privacy\">นโยบายความเป็นส่วนตัว</a></p><h3>7. การเปลี่ยนแปลงข้อกำหนด</h3><p>บริษัทอาจปรับปรุงข้อกำหนดนี้ได้ โดยจะแสดงวันที่ปรับปรุงล่าสุดไว้ท้ายหน้า</p><h3>8. กฎหมายที่ใช้บังคับ</h3><p>ข้อกำหนดนี้อยู่ภายใต้กฎหมายไทย และให้ศาลไทยเป็นผู้มีอำนาจพิจารณาข้อพิพาท</p><p><i>ปรับปรุงล่าสุด: 15 สิงหาคม 2569</i></p>", done: true },
      en: { title: "Terms of Use", body: "<p>These terms apply to your use of jkppropertyagency.com, operated by JKP PROPERTY CO., LTD. By using the site you accept them.</p><h3>1. What the listings are</h3><p>Properties, prices, floor areas and specifications on this site are presented for initial information only and are <b>not a binding offer</b>. Prices and availability change; our team confirms both again before a viewing and before any agreement.</p><h3>2. Do your own checks</h3><p>Before renting or buying, you should verify title documents, the relevant permits (such as the Ror. 4 factory operating licence), zoning, and the physical condition of the property yourself or through your own advisers. We are glad to obtain documents and arrange access, but we cannot warrant the accuracy of paperwork issued by third parties.</p><h3>3. Acceptable use</h3><p>Do not use this site for unlawful purposes, do not scrape it in bulk for commercial reuse, and do not attempt to reach parts of the system that are not published.</p><h3>4. Intellectual property</h3><p>Text, photographs, marks and design on this site belong to the company or to the property owners who licensed them to us. Do not reproduce or republish them commercially without written permission.</p><h3>5. External links</h3><p>The site links to maps and other outside services. We are not responsible for their content or their policies.</p><h3>6. Personal data</h3><p>Collection and use of personal data is governed by our <a href=\"/en/p/privacy\">Privacy Policy</a>.</p><h3>7. Changes</h3><p>We may update these terms; the date at the foot of the page shows when they last changed.</p><h3>8. Governing law</h3><p>These terms are governed by Thai law, and the Thai courts have jurisdiction over any dispute.</p><p><i>Last updated: 15 August 2026</i></p>", done: true },
      zh: { title: "使用条款", body: "<p>本条款适用于您对 jkppropertyagency.com 的访问与使用，网站由 JKP PROPERTY CO., LTD. 运营。使用本网站即表示您接受本条款。</p><h3>1. 房源信息的性质</h3><p>网站上的房源、价格、面积与规格仅供初步参考，<b>不构成具有法律约束力的要约</b>。价格与可租售状态随时可能变动；看房前与签约前，我们的团队都会再次确认。</p><h3>2. 请自行核实</h3><p>在决定租赁或购买前，建议您本人或委托顾问核实产权文件、相关许可（如 ร.ง.4 工厂经营许可证）、城市规划分区以及房产实际状况。我们乐于协助调取文件并安排实地查看，但无法对第三方出具文件的准确性作出保证。</p><h3>3. 合理使用</h3><p>请勿将本网站用于违法目的，请勿大量自动抓取内容用于商业用途，亦请勿尝试访问未公开的系统部分。</p><h3>4. 知识产权</h3><p>网站的文字、照片、标识与设计归本公司或授权我们使用的业主所有。未经书面许可，不得为商业目的复制或转载。</p><h3>5. 外部链接</h3><p>网站包含地图等外部服务链接，我们不对其内容与政策负责。</p><h3>6. 个人资料</h3><p>个人资料的收集与使用适用我们的<a href=\"/zh/p/privacy\">隐私政策</a>。</p><h3>7. 条款变更</h3><p>我们可能更新本条款，页尾会标注最后更新日期。</p><h3>8. 适用法律</h3><p>本条款适用泰国法律，争议由泰国法院管辖。</p><p><i>最后更新：2026 年 8 月 15 日</i></p>", done: true },
    },
  },
  {
    slug: "cookies",
    title: "นโยบายคุกกี้",
    content: {
      th: { title: "นโยบายคุกกี้", body: "<p>นโยบายนี้อธิบายว่าเว็บไซต์ jkppropertyagency.com เก็บอะไรไว้ในเบราว์เซอร์ของท่านบ้าง เก็บไปทำอะไร และท่านเปลี่ยนใจได้อย่างไร ใช้คู่กับ<a href=\"/th/p/privacy\">นโยบายความเป็นส่วนตัว</a></p><h3>1. สรุปสั้น ๆ</h3><p>เว็บไซต์นี้ <b>ไม่มีระบบวิเคราะห์ผู้เข้าชม ไม่มีคุกกี้โฆษณา ไม่มีพิกเซลของโซเชียลมีเดีย และไม่มีการติดตามข้ามเว็บไซต์</b> สิ่งเดียวที่ต้องขอความยินยอมคือแผนที่ Google ที่ฝังอยู่ในหน้าติดต่อเรา</p><h3>2. สิ่งที่จำเป็นต่อการใช้งาน (ไม่ต้องขอความยินยอม)</h3><p><b>jkp_session</b> — คุกกี้ ใช้รักษาสถานะเข้าสู่ระบบของเจ้าหน้าที่ในระบบหลังบ้าน เป็นแบบ HttpOnly ส่งเฉพาะกับเว็บไซต์นี้ ผู้เข้าชมทั่วไปไม่ได้รับคุกกี้นี้</p><p><b>jkp.consent.v1</b> — เก็บในเบราว์เซอร์ (localStorage) บันทึกคำตอบของท่านจากกล่องความยินยอม เพื่อจะได้ไม่ต้องถามซ้ำทุกครั้ง</p><p><b>jkp.favourites.v1</b> — เก็บในเบราว์เซอร์ (localStorage) จดรหัสทรัพย์ที่ท่านกดรูปหัวใจไว้ ข้อมูลนี้อยู่ในเครื่องของท่านเท่านั้น ไม่ถูกส่งมาที่เซิร์ฟเวอร์และเราไม่เห็น</p><h3>3. สิ่งที่ต้องขอความยินยอมก่อน</h3><p><b>แผนที่ Google แบบฝัง (google.com/maps)</b> — อยู่ในหน้าติดต่อเราหน้าเดียว เมื่อโหลด Google จะได้รับหมายเลขไอพีของท่านและอาจสร้างคุกกี้ของ Google เอง <b>ถ้าท่านยังไม่อนุญาต เราจะไม่โหลดแผนที่เลย</b> จะแสดงเป็นปุ่มแทน และท่านยังกดลิงก์ไปเปิดใน Google Maps เองได้</p><h3>4. ฟอนต์</h3><p>ตัวอักษรบนเว็บไซต์โหลดจาก Google Fonts ซึ่ง <b>ไม่สร้างคุกกี้</b> แต่ Google จะเห็นหมายเลขไอพีของผู้เข้าชมในฐานะผู้ให้บริการไฟล์ฟอนต์</p><h3>5. เปลี่ยนใจได้ตลอด</h3><p>กด \"การตั้งค่าคุกกี้\" ที่ท้ายทุกหน้าเพื่อเปิดกล่องตั้งค่าอีกครั้ง จะเปิดหรือปิดเมื่อไรก็ได้ และการลบข้อมูลเว็บไซต์ในเบราว์เซอร์จะล้างทุกอย่างที่กล่าวมาข้างต้น</p><p><i>ปรับปรุงล่าสุด: 15 สิงหาคม 2569</i></p>", done: true },
      en: { title: "Cookie Policy", body: "<p>This policy sets out what jkppropertyagency.com stores in your browser, why, and how to change your mind. Read it alongside our <a href=\"/en/p/privacy\">Privacy Policy</a>.</p><h3>1. The short version</h3><p>This site has <b>no visitor analytics, no advertising cookies, no social media pixels and no cross-site tracking</b>. The only thing we have to ask consent for is the Google map embedded on the contact page.</p><h3>2. Strictly necessary (no consent required)</h3><p><b>jkp_session</b> — a cookie that keeps a staff member signed in to the admin area. HttpOnly and sent only to this site. Ordinary visitors never receive it.</p><p><b>jkp.consent.v1</b> — browser storage holding your answer to the consent dialog, so we do not ask again on every page.</p><p><b>jkp.favourites.v1</b> — browser storage listing the property codes you hearted. It stays on your device; it is never sent to our server and we cannot see it.</p><h3>3. Requires your consent</h3><p><b>Embedded Google map (google.com/maps)</b> — on the contact page only. Loading it gives Google your IP address and lets Google set its own cookies. <b>Until you allow it we do not load the map at all</b>: a button stands in its place, and the link that opens Google Maps in a new tab still works.</p><h3>4. Fonts</h3><p>Type on this site is served by Google Fonts, which <b>sets no cookie</b>, though Google sees a visitor's IP address as the provider of the font files.</p><h3>5. Changing your mind</h3><p>\"Cookie settings\" at the foot of every page reopens the dialog. You may switch the optional item on or off at any time, and clearing this site's data in your browser removes everything listed above.</p><p><i>Last updated: 15 August 2026</i></p>", done: true },
      zh: { title: "Cookie 政策", body: "<p>本政策说明 jkppropertyagency.com 在您的浏览器中存放了哪些内容、用途为何，以及您如何更改选择。请与<a href=\"/zh/p/privacy\">隐私政策</a>一并阅读。</p><h3>1. 简要说明</h3><p>本网站<b>没有访客分析、没有广告 Cookie、没有社交媒体像素，也没有跨站追踪</b>。唯一需要征得同意的，是\"联系我们\"页面内嵌的 Google 地图。</p><h3>2. 必要项目（无需同意）</h3><p><b>jkp_session</b> — Cookie，用于保持管理人员的后台登录状态。设为 HttpOnly，且只发送至本站。普通访客不会收到。</p><p><b>jkp.consent.v1</b> — 浏览器本地存储，记录您在同意对话框中的选择，避免每页重复询问。</p><p><b>jkp.favourites.v1</b> — 浏览器本地存储，记录您收藏（点击爱心）的房源编号。仅保存在您的设备上，不会发送至我们的服务器，我们也无法查看。</p><h3>3. 需要您同意的项目</h3><p><b>内嵌 Google 地图（google.com/maps）</b> — 仅出现在联系页面。加载时 Google 会取得您的 IP 地址，并可能写入 Google 自己的 Cookie。<b>在您允许之前，我们完全不加载该地图</b>，页面上以按钮代替；另外\"在 Google 地图中打开\"的链接仍可正常使用。</p><h3>4. 字体</h3><p>网站字体由 Google Fonts 提供，<b>不写入 Cookie</b>，但 Google 作为字体文件的提供方会看到访客的 IP 地址。</p><h3>5. 更改选择</h3><p>点击每页页尾的\"Cookie 设置\"即可再次打开对话框，随时开启或关闭可选项目；在浏览器中清除本站数据，即可移除上述全部内容。</p><p><i>最后更新：2026 年 8 月 15 日</i></p>", done: true },
    },
  },
];
